services:
  yt_transcript:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8885:8000"
    environment:
      - DB_PATH=/data/transcripts.db
      - WEBSHARE_USERNAME=${WEBSHARE_USERNAME}
      - WEBSHARE_PASSWORD=${WEBSHARE_PASSWORD}
    volumes:
      - ./data:/data
    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
